platform :ios, '10.3'
use_frameworks!

target 'RemoteConfigRxWrapper_Example' do
  pod 'RemoteConfigRxWrapper', :path => '../'
  pod 'RxCocoa', '~> 4.2.0'
  pod 'RxOptional', '~> 3.5.0'

  target 'RemoteConfigRxWrapper_Tests' do
    inherit! :search_paths
    pod 'RxTest', '~> 4.2.0'
  end
end
